### ISSUE TITLE
[Question] the app fails when i try to enter a name and press Greet `window.__TAURI_IPC__ is not a function`

### ISSUE THREAD

**Issue by simkimsia** [JonasKruckenberg/tauri-astro-template#22]
when i do that in localhost:4321 i keep getting

tauri.js:55  Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    at tauri.js:55:16
    at new Promise (<anonymous>)
    at invoke (tauri.js:46:12)
    at HTMLButtonElement.greet (Greet.svelte:7:24)
    
same thing with the app window
    
<img width="1362" alt="image" src="https://github.com/JonasKruckenberg/tauri-astro-template/assets/245021/05c8b47e-f176-4671-99b3-74ad35e4147e">

when I  `rustc --version`
I get `rustc 1.74.1 (a28077b28 2023-12-04)`

I have found this issue https://github.com/tauri-apps/tauri/issues/3434, but i still am not too sure how to solve this issue

**Comment by mateuszruszkowski** [comment]
I see this problem has been around for a long time, but I thought it was only on Windows. Run through `pnpm tauri dev` it should run. I think the problem is how we define the project when we initialize it

**Comment by JonasKruckenberg** [comment]
Whatever the solution to your problem was I hope you figured it out! If not you should open an issue on the Tauri repo itself or head to our discord, this is not an issue with the template itself.
