### ISSUE TITLE
Template update for Tauri v2

### ISSUE THREAD

**Issue by davegomez** [JonasKruckenberg/tauri-astro-template#27]
@JonasKruckenberg are you planning to update the template to work with Tauri v2?

I haven't tried the template because I just found the project using my phone, so I'm sorry if it's already working with it and I'm wasting your time with this questions.

Why don't you include this template in the [awesome-tauri](https://github.com/tauri-apps/awesome-tauri) repository?

Is it possible to provide steps in the README to move/migrate an existing Astro project to work within Tauri?

**Comment by JonasKruckenberg** [comment]
Well I wasn't originally, as I don't really have the time to maintain any of these templates :/ buuuuut I had a few minutes on my hands today and just pushed the relevant changes! Hope it helps you!

As for why I didn't submit this, again, don't really have the time and I did this template as a quick one-off originally. 

Migrating an existing astro project should be exactly like migrating any existing project, so [these steps](https://beta.tauri.app/guides/create/#manual-setup-using-the-tauri-cli) should be all there as
